-- 코드를 입력하세요
WITH SALES AS (
    SELECT AUTHOR_ID, 
            CATEGORY, 
            SUM(PRICE * SALES) AS TOTAL_SALES
    FROM BOOK B
    INNER JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
    WHERE S.SALES_DATE LIKE '2022-01%'
    GROUP BY AUTHOR_ID, CATEGORY)
    
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, TS.CATEGORY, TS.TOTAL_SALES
FROM AUTHOR A
INNER JOIN SALES TS
ON A.AUTHOR_ID = TS.AUTHOR_ID
ORDER BY A.AUTHOR_ID, TS.CATEGORY DESC
;