-- 코드를 작성해주세요
WITH PARENT AS (
    SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT
    FROM ECOLI_DATA 
    GROUP BY PARENT_ID)
    
SELECT ID, IFNULL(CHILD_COUNT,0) AS CHILD_COUNT
FROM ECOLI_DATA
LEFT JOIN PARENT P 
ON ID = P.PARENT_ID
ORDER BY ID;