-- 코드를 입력하세요
WITH OVER_THREE AS (
    SELECT WRITER_ID, COUNT(*) AS COUNT
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
    HAVING COUNT >= 3)

SELECT USER_ID, 
        NICKNAME, 
        CONCAT(CITY,' ', 
               STREET_ADDRESS1, ' ', 
               STREET_ADDRESS2) AS '전체주소', 
        CONCAT(SUBSTRING(TLNO, 1, 3), '-', 
            SUBSTRING(TLNO, 4, 4), '-', 
            SUBSTRING(TLNO, 8)) AS '전화번호'
FROM USED_GOODS_USER USERS
INNER JOIN OVER_THREE OT
ON USERS.USER_ID = OT.WRITER_ID
ORDER BY USER_ID DESC
;
