-- 코드를 입력하세요
WITH USERS2021 AS (
    SELECT *
    FROM USER_INFO 
    WHERE JOINED LIKE '2021-%'
)
                  
SELECT YEAR(SALES.SALES_DATE) AS YEAR, 
        MONTH(SALES.SALES_DATE) AS MONTH,
        COUNT(DISTINCT SALES.USER_ID) AS PUCHASED_USERS,
        ROUND(COUNT(DISTINCT SALES.USER_ID) / (SELECT COUNT(*) FROM USERS2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE SALES
INNER JOIN USERS2021
ON SALES.USER_ID = USERS2021.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;