-- 코드를 입력하세요
WITH HEAVY_USERS AS (
    SELECT HOST_ID, COUNT(*) AS COUNT
    FROM PLACES 
    GROUP BY HOST_ID
    HAVING COUNT >= 2)
SELECT ID, NAME, HU.HOST_ID
FROM PLACES P
INNER JOIN HEAVY_USERS HU
WHERE P.HOST_ID = HU.HOST_ID;