-- 코드를 입력하세요
WITH SUB AS (
    SELECT HISTORY_ID, H.CAR_ID, CAR_TYPE, DAILY_FEE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION,
    CASE
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
        WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON H.CAR_ID = C.CAR_ID
WHERE CAR_TYPE LIKE '트럭')

SELECT HISTORY_ID, ROUND(DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100  * DURATION) AS FEE
FROM SUB 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON SUB.CAR_TYPE = P.CAR_TYPE AND
    SUB.DURATION_TYPE = P. DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;