-- 코드를 입력하세요
SELECT APNT_NO,	
        PT_NAME, 
        A.PT_NO, 
        A.MCDP_CD, 
        DR_NAME, 
        APNT_YMD
FROM APPOINTMENT A
INNER JOIN PATIENT P ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR D ON DR_ID = MDDR_ID
WHERE A.MCDP_CD LIKE 'CS' AND
      APNT_CNCL_YN LIKE 'N' AND
      APNT_YMD LIKE '2022-04-13%'
ORDER BY APNT_YMD;