-- 코드를 입력하세요
SELECT USERS.USER_ID, USERS.NICKNAME, SUM(GOODS.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER USERS
INNER JOIN USED_GOODS_BOARD GOODS
ON USERS.USER_ID = GOODS.WRITER_ID
WHERE GOODS.STATUS = 'DONE'
GROUP BY USERS.USER_ID, GOODS.WRITER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;