-- 코드를 입력하세요
SELECT MOST_ONE.MEMBER_NAME, REVIEWS.REVIEW_TEXT, DATE_FORMAT(REVIEWS.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW REVIEWS
INNER JOIN (SELECT REVIEWS.MEMBER_ID, MEMBERS.MEMBER_NAME, COUNT(*) AS REVIEWS
    FROM REST_REVIEW REVIEWS
    INNER JOIN MEMBER_PROFILE MEMBERS
    ON MEMBERS.MEMBER_ID = REVIEWS.MEMBER_ID
    GROUP BY MEMBER_ID
    ORDER BY REVIEWS DESC
    LIMIT 1) MOST_ONE
ON MOST_ONE.MEMBER_ID = REVIEWS.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEWS.REVIEW_TEXT;