-- 코드를 입력하세요
WITH SEDAN AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_CAR 
    WHERE CAR_TYPE LIKE '세단')

SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN SEDAN S
ON S.CAR_ID = H.CAR_ID
WHERE MONTH(START_DATE) LIKE '10'
ORDER BY H.CAR_ID DESC
;