-- 코드를 작성해주세요
WITH BIGGEST AS (
    SELECT N.FISH_TYPE, N.FISH_NAME, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO I
    INNER JOIN FISH_NAME_INFO N
    ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_NAME, N.FISH_TYPE)
    
SELECT I.ID, B.FISH_NAME, I.LENGTH
FROM BIGGEST B
INNER JOIN FISH_INFO I
ON I.FISH_TYPE = B.FISH_TYPE AND B.LENGTH = I.LENGTH
ORDER BY ID;
    
