-- 코드를 작성해주세요
WITH AVG_SAL AS (
    SELECT DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID)

SELECT D.DEPT_ID, D.DEPT_NAME_EN, AVG_SAL
FROM HR_DEPARTMENT D
INNER JOIN AVG_SAL
ON D.DEPT_ID = AVG_SAL.DEPT_ID
ORDER BY AVG_SAL DESC
;