SELECT BOOK.CATEGORY, SUM(SALES.SALES) AS TOTAL_SALES
FROM BOOK_SALES SALES
INNER JOIN BOOK
ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE SALES.SALES_DATE LIKE '2022-01%'
GROUP BY BOOK.CATEGORY
ORDER BY BOOK.CATEGORY;