-- 코드를 입력하세요
WITH EXPENSIVE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY)
    
SELECT P.CATEGORY,	E.MAX_PRICE,	P.PRODUCT_NAME
FROM FOOD_PRODUCT P
INNER JOIN EXPENSIVE E
ON E.MAX_PRICE = P.PRICE AND P.CATEGORY = E.CATEGORY
ORDER BY MAX_PRICE DESC;