-- 코드를 작성해주세요
WITH OVER_AVG AS (
    SELECT FISH_TYPE, AVG(LENGTH) AS AVERAGE
    FROM FISH_INFO 
    GROUP BY FISH_TYPE
    HAVING AVERAGE >= 33)
    
SELECT COUNT(I.ID) AS FISH_COUNT, 
        MAX(I.LENGTH) AS MAX_LENGTH, 
        I.FISH_TYPE
FROM FISH_INFO I
INNER JOIN OVER_AVG OA
ON OA.FISH_TYPE = I.FISH_TYPE
GROUP BY I.FISH_TYPE
ORDER BY I.FISH_TYPE;